<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $guarded = [];

    protected $touches = [ 'project' ];

    protected $casts = [

        'completed' => 'boolean'
    ];

    // Overriding the 'boot' method in a model is a way to override the various lifecycle hooks of a model within it.
    // this is an alternative approach to using a dedicated Model Observer, which this was refactored to use..

    // protected static function boot()
    // {
    //     parent::boot(); // TODO: change the autogenerated stub

    //     static::created( function( $task ){

    //         $task->project->recordActivity( 'created_task' );
    //     });

    //     static::deleted( function( $task ) {

    //         $task->project->recordActivity( 'deleted_task' );
    //     });
    //     // static::updated( function( $task ){

    //         // if( !$task->completed ) return;
    //         // $task->project->recordActivity( 'completed_task' );
    //     // });
    // }

    public function complete()
    {

        $this->update([ 'completed' => true ]);
        $this->project->recordActivity( 'completed_task' );
    }

    public function incomplete()
    {

        $this->update([ 'completed' => false ]);
        $this->project->recordActivity( 'incompleted_task' );
    }

    public function project()
    {

        return $this->belongsTo( Project::class );
    }

    public function path()
    {

        return '/projects/' . $this->project->id . '/tasks/' . $this->id;
    }
}
